/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + environment + loaded contracts. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a multi-source pipeline run.
         * @description Accepts one or more ingestion sources plus optional constraints, allocates a pipeline_id (PIPE-XXXXXXXX), and (Phase 4+) routes the request to the orchestrator. The current handler returns a synchronous stub envelope; trace/HITL state is observable via the other endpoints once the orchestrator runs.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PipelineRunRequest"];
                };
            };
            responses: {
                /** @description Run accepted (stub envelope while orchestrator is wired). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PipelineRunResponse"];
                    };
                };
                /** @description sources array missing or empty. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "sources array is required and must not be empty"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unhandled server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full pipeline trace. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Pipeline identifier returned by POST /api/pipeline/run.
                     * @example PIPE-7K2A9F31
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pipeline trace. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PipelineTrace"];
                    };
                };
                /** @description Pipeline id not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Pipeline not found"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Antigravity trace export (judge-facing).
         * @description Identical shape to GET /api/pipeline/:id; provided as a stable export alias.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Pipeline identifier returned by POST /api/pipeline/run.
                     * @example PIPE-7K2A9F31
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pipeline trace export. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PipelineTrace"];
                    };
                };
                /** @description Pipeline trace not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of pipeline TraceEvent frames.
         * @description Long-lived text/event-stream connection. Each `data:` frame is a JSON-serialized TraceEvent. Emits an `end` event when the trace is finalized. Heartbeat comments keep the connection alive while the pipeline is starting.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Pipeline identifier returned by POST /api/pipeline/run.
                     * @example PIPE-7K2A9F31
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream open. Frames are TraceEvent JSON objects. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["TraceEvent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline/{id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compiled analytics for a pipeline.
         * @description 404 while the multi-agent pool is still synthesizing; 200 once the AMCE-judged PipelineAnalytics record lands in the cache.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Pipeline identifier returned by POST /api/pipeline/run.
                     * @example PIPE-7K2A9F31
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analytics ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PipelineAnalytics"];
                    };
                };
                /** @description Sub-agents still processing. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all loaded YAML contracts (summary). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Loaded contracts. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contracts: components["schemas"]["ContractSummary"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full contract definition by name. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Contract slug, e.g. action_chain_v1 or workflow_audit_v1.
                     * @example action_chain_v1
                     */
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contract definition. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContractDefinition"];
                    };
                };
                /** @description Contract not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Contract not found: foo_v1"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All contract_gate events grouped by pipeline. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Validation events. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution/{id}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect a pipeline blocked at the HITL approval gate.
         * @description Returns the full PipelineApprovalRecord when the pipeline is in state PENDING. If the pipeline exists but has already transitioned (EXECUTING/REJECTED/COMPLETED), the gate is closed and the endpoint responds 409 with the current state — this is the strict state-machine invariant enforced by pipelineApprovalStore.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Pipeline identifier returned by POST /api/pipeline/run.
                     * @example PIPE-7K2A9F31
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pipeline is PENDING — proposal payload returned for the approval card. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "pipeline_id": "PIPE-7K2A9F31",
                         *       "state": "PENDING",
                         *       "proposed_at": "2026-05-16T14:22:08.114Z",
                         *       "proposal": {
                         *         "proposedActions": [
                         *           {
                         *             "action_id": "ACT-9F3X2B",
                         *             "title": "Roll out feature flag to 5% cohort",
                         *             "description": "Gradual rollout to validate latency under prod load.",
                         *             "priority": "HIGH",
                         *             "depends_on": []
                         *           }
                         *         ],
                         *         "rationale": "Within the 30-day horizon, projected latency dominates risk.",
                         *         "overall_priority": "HIGH"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["PipelineApprovalRecord"];
                    };
                };
                /** @description Pipeline id unknown. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Pipeline not found"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Pipeline exists but is not in PENDING state. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Pipeline is EXECUTING, not PENDING",
                         *       "pipeline_id": "PIPE-7K2A9F31",
                         *       "current_state": "EXECUTING"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execution/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a PENDING pipeline (atomic PENDING -> EXECUTING).
         * @description Atomic check-and-set: only a pipeline in state PENDING can transition to EXECUTING. Concurrent approval attempts on the same pipeline serialize through the in-memory store; the loser receives 409. The request body must include a non-empty approver signature name (`approved_by`); the value is recorded on the PipelineApprovalRecord and surfaces in the downstream WorkflowAudit signature_block.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Pipeline identifier returned by POST /api/pipeline/run.
                     * @example PIPE-7K2A9F31
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveRequest"];
                };
            };
            responses: {
                /** @description Approved — pipeline activated for execution. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "pipeline_id": "PIPE-7K2A9F31",
                         *       "state": "EXECUTING",
                         *       "approved_by": "alex.chen",
                         *       "approved_at": "2026-05-16T14:25:01.902Z"
                         *     }
                         */
                        "application/json": components["schemas"]["ApproveResponse"];
                    };
                };
                /** @description Missing or empty `approved_by`. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "approved_by (non-empty string) required in body"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Pipeline id unknown. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Pipeline PIPE-7K2A9F31 not found",
                         *       "pipeline_id": "PIPE-7K2A9F31"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Atomic concurrency lock — pipeline is not PENDING (e.g. already EXECUTING due to a prior approve, or REJECTED/COMPLETED). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Pipeline PIPE-7K2A9F31 is EXECUTING, not PENDING",
                         *       "pipeline_id": "PIPE-7K2A9F31"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description State machine for the HITL approval gate. Only PENDING -> EXECUTING is reachable via POST /api/execution/:id/approve (atomic check-and-set).
         * @example PENDING
         * @enum {string}
         */
        ApprovalState: "PENDING" | "EXECUTING" | "REJECTED" | "COMPLETED";
        /**
         * @example HIGH
         * @enum {string}
         */
        Priority: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
        ProposedAction: {
            /** @example ACT-9F3X2B */
            action_id: string;
            /** @example Roll out feature flag to 5% cohort */
            title: string;
            /** @example Gradual rollout to validate latency impact under production load. */
            description: string;
            priority: components["schemas"]["Priority"];
            /**
             * @example [
             *       "ACT-A1B2C3"
             *     ]
             */
            depends_on: string[];
        };
        StrategyProposal: {
            proposedActions: components["schemas"]["ProposedAction"][];
            /**
             * @description Must reference at least one forecast horizon (30/60/90-day).
             * @example Within the 30-day horizon, projected user-reported latency dominates risk; staged rollout mitigates blast radius.
             */
            rationale: string;
            overall_priority: components["schemas"]["Priority"];
        };
        /** @description Canonical 200 payload of GET /api/execution/:id/pending. Mirrors src/stores/pipeline-approval.store.ts. */
        PipelineApprovalRecord: {
            /** @example PIPE-7K2A9F31 */
            pipeline_id: string;
            state: components["schemas"]["ApprovalState"];
            /**
             * Format: date-time
             * @example 2026-05-16T14:22:08.114Z
             */
            proposed_at: string;
            /**
             * Format: date-time
             * @example 2026-05-16T14:25:01.902Z
             */
            approved_at?: string | null;
            /** @example alex.chen */
            approved_by?: string | null;
            proposal: components["schemas"]["StrategyProposal"];
        };
        ApproveRequest: {
            /**
             * @description Human approver signature name (operator handle). Trimmed; empty string yields 400.
             * @example alex.chen
             */
            approved_by: string;
        };
        ApproveResponse: {
            /** @example PIPE-7K2A9F31 */
            pipeline_id: string;
            state: components["schemas"]["ApprovalState"];
            /** @example alex.chen */
            approved_by: string;
            /**
             * Format: date-time
             * @example 2026-05-16T14:25:01.902Z
             */
            approved_at: string;
        };
        ErrorEnvelope: {
            /** @example Pipeline PIPE-7K2A9F31 is EXECUTING, not PENDING */
            error: string;
            pipeline_id?: string | null;
            current_state?: components["schemas"]["ApprovalState"];
        };
        ExecutionResult: {
            /** @example ACT-9F3X2B */
            action_id: string;
            /**
             * @example SUCCESS
             * @enum {string}
             */
            status: "SUCCESS" | "FAILED" | "SKIPPED";
            /** @example 412 */
            latency_ms: number;
            /** @example Upstream 5xx */
            error_message?: string | null;
            /** @example Flag activated for cohort=tier-1 */
            output_summary?: string | null;
        };
        /** @description Module 11 (action_chain_v1) — unified execution result for the HITL-approved, topologically-sorted action chain. */
        ActionChain: {
            /** @example PIPE-7K2A9F31 */
            pipelineId: string;
            /**
             * @description SUCCESS only if every execution_results.status === SUCCESS; FAILED only if no result is SUCCESS; otherwise PARTIAL_SUCCESS.
             * @example PARTIAL_SUCCESS
             * @enum {string}
             */
            overall_status: "SUCCESS" | "PARTIAL_SUCCESS" | "FAILED";
            /** @example alex.chen */
            approved_by?: string | null;
            /**
             * Format: date-time
             * @example 2026-05-16T14:25:01.902Z
             */
            approval_timestamp: string;
            /** @example 2871 */
            total_execution_ms: number;
            execution_results: components["schemas"]["ExecutionResult"][];
        };
        RecoveryPlanEntry: {
            /** @example ACT-9F3X2B */
            intercepted_action_id: string;
            /**
             * @example RETRY
             * @enum {string}
             */
            applied_strategy: "RETRY" | "FALLBACK" | "SKIP";
            /**
             * @example RESOLVED
             * @enum {string}
             */
            mitigation_status: "PROPOSED" | "BLOCKED" | "RESOLVED";
            /** @example Transient 503; exponential backoff cleared on second attempt. */
            rationale: string;
        };
        /** @description Module 12 (failure_recovery_v1) — recovery strategies mapped onto FAILED upstream actions, with cascaded skips. */
        FailureRecovery: {
            /** @example PIPE-7K2A9F31 */
            pipelineId: string;
            recovery_plan: components["schemas"]["RecoveryPlanEntry"][];
            /**
             * @example [
             *       "ACT-DEAD01"
             *     ]
             */
            cascaded_skips: string[];
        };
        /** @description Module 13 (outcome_visualization_v1) — quantitative before/after deltas and qualitative impact projection. */
        OutcomeVisualization: {
            /** @example PIPE-7K2A9F31 */
            pipelineId: string;
            /** @example 142.5 */
            total_cost: number;
            /**
             * @description Inclusive percent reduction in projected incident risk.
             * @example 37.2
             */
            projected_risk_reduction: number;
            /**
             * @description Milliseconds saved on the critical path under the simulated chain.
             * @example 184
             */
            simulated_latency_saved: number;
            /** @example P95 latency 1820ms; 2 actions in degraded state. */
            before_state_summary: string;
            /** @example P95 latency 1636ms; all critical actions SUCCESS. */
            after_state_summary: string;
            /**
             * @description Must reference at least one ACT- action_id from the execution chain.
             * @example ACT-9F3X2B reduced cold-start latency; ACT-A1B2C3 narrowed the affected cohort.
             */
            qualitative_diff: string;
        };
        SignatureBlock: {
            /** @example alex.chen */
            approver: string;
            /** @example PIPE-7K2A9F31 */
            pipeline_id: string;
            /**
             * Format: date-time
             * @example 2026-05-16T14:25:01.902Z
             */
            signed_at: string;
        };
        /** @description Numeric counters of pipeline-trace events. Must include the five canonical keys at minimum. */
        EventSummary: {
            /** @example 14 */
            agent_start: number;
            /** @example 14 */
            agent_complete: number;
            /** @example 6 */
            action_start: number;
            /** @example 5 */
            action_complete: number;
            /** @example 14 */
            contract_gate: number;
        } & {
            [key: string]: number;
        };
        /** @description Module 14 (workflow_audit_v1) — consolidated compliance receipt with SHA-256 verification hash. */
        WorkflowAudit: {
            /** @example PIPE-7K2A9F31 */
            pipelineId: string;
            /** @example AUD-9F3X2B7K */
            audit_id: string;
            /**
             * Format: date-time
             * @example 2026-05-16T14:25:09.741Z
             */
            generated_at: string;
            /**
             * @description Mirrors upstream ActionChain.overall_status (SUCCESS->APPROVED_PASSED, PARTIAL_SUCCESS->APPROVED_PARTIAL, FAILED->APPROVED_FAILED).
             * @example APPROVED_PARTIAL
             * @enum {string}
             */
            finalized_status: "APPROVED_PASSED" | "APPROVED_PARTIAL" | "APPROVED_FAILED" | "REJECTED";
            signature_block: components["schemas"]["SignatureBlock"];
            /**
             * @description Lowercase 64-char hex SHA-256 digest covering the canonical receipt body.
             * @example a3f1c4e9b27d80516fb24ce8d1972a4c3e0bff62a9d7a1c4519b8e7a3c0d6e9f
             */
            verification_hash: string;
            event_summary: components["schemas"]["EventSummary"];
        };
        MultiSourceIngestionSource: {
            /** @example SRC-001 */
            source_id: string;
            /**
             * @example url
             * @enum {string}
             */
            source_type: "pdf" | "url" | "csv" | "txt" | "json" | "realtime_feed";
            /** @example https://example.com/incident-report */
            content: string;
            /**
             * @example HIGH
             * @enum {string}
             */
            credibility_tier?: "HIGH" | "MEDIUM" | "LOW" | "UNVERIFIED";
            /**
             * Format: date-time
             * @example 2026-05-16T14:21:42.001Z
             */
            ingested_at: string;
        };
        /** @description Ingestion contract (multi_source_ingestion_v1) — upstream context fed into POST /api/pipeline/run. */
        MultiSourceIngestion: {
            /** @example ING-7K2A9F31 */
            ingestion_id: string;
            /** Format: date-time */
            timestamp: string;
            /** @example 3 */
            sources_processed: number;
            sources: components["schemas"]["MultiSourceIngestionSource"][];
        };
        /** @description Generic YAML contract shape returned by GET /api/contracts/:name. Field semantics vary per contract. */
        ContractDefinition: {
            /** @example action_chain_v1 */
            name: string;
            /** @example 1.0 */
            version: string;
            /** @example ExecutionSimulatorAgent */
            module: string;
            description: string;
            fields: {
                [key: string]: unknown;
            };
            semantic_checks?: string[];
        } & {
            [key: string]: unknown;
        };
        ContractSummary: {
            /** @example action_chain_v1 */
            name: string;
            /** @example 1.0 */
            version: string;
            /** @example ExecutionSimulatorAgent */
            module: string;
            description: string;
            /** @example 6 */
            field_count: number;
        };
        TraceEvent: {
            /** Format: uuid */
            event_id: string;
            pipeline_id: string;
            /** Format: date-time */
            timestamp: string;
            /** @enum {string} */
            event_type: "agent_start" | "agent_complete" | "llm_call" | "contract_gate" | "action_execute" | "failure" | "ingestion_error" | "recovery" | "decision" | "action_start" | "action_complete" | "graph_cycle_detected" | "hitl_pending" | "hitl_approved" | "thinking";
            /** @example StrategicRecommenderAgent */
            agent: string;
            message: string;
            data?: {
                [key: string]: unknown;
            };
            decision?: string;
            confidence?: number;
            /** @example gemini-free */
            provider?: string;
            latency_ms?: number;
        };
        ForecastPoint: {
            /** Format: date-time */
            timestamp: string;
            value: number;
            /** @description True beyond the current cursor (predicted region). */
            is_extrapolation: boolean;
        };
        ContradictionRecord: {
            /** @example SRC-001 */
            source_id: string;
            /** Format: date-time */
            timestamp: string;
            raw_claim: string;
            baseline_context: string;
            conflict_rationale: string;
        };
        /** @description AMCE-judged analytics payload returned by GET /api/pipeline/:id/analytics. forecast_data carries 30 historical + 60 predicted points. */
        PipelineAnalytics: {
            extrapolation_unreliable: boolean;
            forecast_data: components["schemas"]["ForecastPoint"][];
            contradictions: components["schemas"]["ContradictionRecord"][];
        };
        /** @description Full pipeline trace returned by GET /api/pipeline/:id and /api/pipeline/:id/trace. Mirrors src/tracing/collector.ts. */
        PipelineTrace: {
            pipeline_id: string;
            /** @example development */
            environment: string;
            /** @example gemini-free */
            ai_provider_used: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            workplan: string;
            task_plan: string[];
            reasoning_steps: {
                step: number;
                agent: string;
                reasoning: string;
                decision: string;
                confidence: number;
            }[];
            tool_calls: {
                tool: string;
                provider: string;
                input_summary: string;
                output_summary: string;
                latency_ms: number;
            }[];
            action_execution: components["schemas"]["TraceEvent"][];
            recovery_steps: string[];
            events: components["schemas"]["TraceEvent"][];
        };
        PipelineRunRequest: {
            sources: components["schemas"]["MultiSourceIngestionSource"][];
            /**
             * @example {
             *       "max_actions": 10,
             *       "forbidden_action_types": [
             *         "IRREVERSIBLE_DELETE"
             *       ]
             *     }
             */
            constraints?: {
                [key: string]: unknown;
            };
        };
        PipelineRunResponse: {
            /** @example PIPE-7K2A9F31 */
            pipeline_id: string;
            /** @example received */
            status: string;
            message?: string;
            sources_received?: number;
            constraints_received?: {
                [key: string]: unknown;
            };
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** @example development */
            environment: string;
            /** @example gemini-free */
            provider: string;
            contracts_loaded: string[];
            /** Format: date-time */
            timestamp: string;
        };
        ValidationsResponse: {
            validations: {
                pipeline_id: string;
                events: components["schemas"]["TraceEvent"][];
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
